### ISSUE TITLE
Registration time about VICET

### ISSUE THREAD

**Issue by JACKLiuDay** [mcdermatt/VICET#1]
Hi, thank you for your great work about VICET. I read your paper. But I did not see any registration time about VICET. Does VICET faster than NDT or ICP or FASTVGICP.

**Comment by mcdermatt** [comment]
Thanks! Theoretically, VICET should be able to run in real time, however, at a registration rate slightly slower than a traditional fast NDT or ICP implementation. The precursor algorithm for VICET, [ICET](https://github.com/mcdermatt/ICET), is shared with a cpp ROS package capable of running between 15-50Hz depending on hardware, hyperparameters, and sensor resolution. Similar to ICET, the most computationally intensive part of each loop iteration is in the fitting of Gaussians, not in actually solving the WLS problem. Though we are solving for 12 states in VICET compared to 6 states in ICET, the time required for inversion step is negligible. The real difference in runtime performance comes from the fact that the 12 state problem is more highly nonlinear and requires careful consideration of step size between iterations to prevent numerical instability. This can be accomplished via Levenberg-Marquardt optimization or by simply scaling down solution contributions at each iteration. Either way, this results in needing to run the algorithm for a higher number of iterations to achieve convergence than a typical rigid registration algorithm. For the experiments in our paper, we found 20-30 iterations were required for stable convergence, while ICET may only need 5-10 iterations on a similar scene.
